// Unit database for Tactics Skirmish (Yu-Gi-Oh reskin).
// Loaded via <script> before the main game script — keep this a plain global,
// no import/export, so the game still runs by just opening index.html.
//
// cost is always the monster's real Duel Monsters Level/Star rating (not an
// independently chosen value). It is reserved for a future army-budget /
// team-selection system and is not yet consumed by any current game logic.
//
// effect is a plain-language description of the unit's battle ability,
// shown in the UI. The actual behavior is implemented in index.html.

const UNIT_DATABASE = {
  kuriboh: {
    name: 'Kuriboh',
    cost: 1,
    hp: 20,
    atk: 6,
    move: 4,
    range: 1,
    type: 'Fiend',
    attribute: 'DARK',
    effect: 'The first attack that would ever damage this unit is negated instead.',
  },
  giant_soldier_of_stone: {
    name: 'Giant Soldier of Stone',
    cost: 3,
    hp: 70,
    atk: 11,
    move: 2,
    range: 1,
    type: 'Rock',
    attribute: 'EARTH',
    effect: 'Adjacent allies take 25% less damage.',
  },
  baby_dragon: {
    name: 'Baby Dragon',
    cost: 3,
    hp: 40,
    atk: 13,
    move: 4,
    range: 1,
    type: 'Dragon',
    attribute: 'WIND',
    effect: 'Gains +3 ATK permanently for each enemy it destroys.',
  },
  celtic_guardian: {
    name: 'Celtic Guardian',
    cost: 4,
    hp: 58,
    atk: 16,
    move: 3,
    range: 1,
    type: 'Warrior',
    attribute: 'EARTH',
    effect: 'If it survives being attacked by an adjacent enemy, strikes back for 50% of its ATK.',
  },
  mystical_elf: {
    name: 'Mystical Elf',
    cost: 4,
    hp: 80,
    atk: 9,
    move: 2,
    range: 2,
    type: 'Spellcaster',
    attribute: 'LIGHT',
    effect: "Heals its most wounded adjacent ally for 10 HP at the start of each of its side's turns.",
  },
  gemini_elf: {
    name: 'Gemini Elf',
    cost: 4,
    hp: 44,
    atk: 19,
    move: 3,
    range: 2,
    type: 'Spellcaster',
    attribute: 'EARTH',
    effect: 'Can attack twice per turn.',
  },
  gaia_fierce_knight: {
    name: 'Gaia the Fierce Knight',
    cost: 7,
    hp: 100,
    atk: 24,
    move: 3,
    range: 1,
    type: 'Warrior',
    attribute: 'EARTH',
    effect: 'Deals 25% bonus damage on turns it moved before attacking.',
  },
  dark_magician: {
    name: 'Dark Magician',
    cost: 7,
    hp: 55,
    atk: 26,
    move: 3,
    range: 3,
    type: 'Spellcaster',
    attribute: 'DARK',
    effect: 'Attacks hit every enemy sharing its row or column within range, not just one target.',
  },
  man_eater_bug: {
    name: 'Man-Eater Bug',
    cost: 2,
    hp: 28,
    atk: 8,
    move: 3,
    range: 1,
    type: 'Insect',
    attribute: 'EARTH',
    effect: 'When destroyed, deals damage equal to its max HP to whoever destroyed it.',
  },
  silver_fang: {
    name: 'Silver Fang',
    cost: 3,
    hp: 38,
    atk: 14,
    move: 4,
    range: 1,
    type: 'Beast',
    attribute: 'WATER',
    effect: 'Gains +4 ATK for each adjacent living Beast-type ally.',
  },
  kaiser_sea_horse: {
    name: 'Kaiser Sea Horse',
    cost: 4,
    hp: 66,
    atk: 15,
    move: 2,
    range: 1,
    type: 'Sea Serpent',
    attribute: 'LIGHT',
    effect: 'Gains +6 ATK while adjacent to Blue-Eyes White Dragon (and grants the same to it).',
  },
  beaver_warrior: {
    name: 'Beaver Warrior',
    cost: 4,
    hp: 70,
    atk: 12,
    move: 2,
    range: 1,
    type: 'Beast-Warrior',
    attribute: 'EARTH',
    effect: "Takes 30% less damage on turns it doesn't move.",
  },
  feral_imp: {
    name: 'Feral Imp',
    cost: 4,
    hp: 56,
    atk: 17,
    move: 3,
    range: 1,
    type: 'Fiend',
    attribute: 'DARK',
    effect: 'Deals 40% bonus damage to targets below half HP.',
  },
  flame_swordsman: {
    name: 'Flame Swordsman',
    cost: 5,
    hp: 62,
    atk: 20,
    move: 3,
    range: 1,
    type: 'Warrior',
    attribute: 'FIRE',
    effect: 'On kill, deals splash damage (50% ATK) to enemies adjacent to the target.',
  },
  curse_of_dragon: {
    name: 'Curse of Dragon',
    cost: 5,
    hp: 52,
    atk: 23,
    move: 3,
    range: 1,
    type: 'Dragon',
    attribute: 'DARK',
    effect: 'Can move through occupied tiles (must still land on an empty one).',
  },
  summoned_skull: {
    name: 'Summoned Skull',
    cost: 6,
    hp: 50,
    atk: 27,
    move: 2,
    range: 1,
    type: 'Fiend',
    attribute: 'DARK',
    effect: 'Its attacks ignore enemy damage-reduction effects.',
  },
  dark_magician_girl: {
    name: 'Dark Magician Girl',
    cost: 6,
    hp: 48,
    atk: 22,
    move: 3,
    range: 2,
    type: 'Spellcaster',
    attribute: 'DARK',
    effect: 'Gains +2 ATK for every allied unit destroyed so far this battle.',
  },
  blue_eyes_white_dragon: {
    name: 'Blue-Eyes White Dragon',
    cost: 8,
    hp: 85,
    atk: 30,
    move: 3,
    range: 1,
    type: 'Dragon',
    attribute: 'LIGHT',
    effect: 'Deals 30% bonus damage to targets not at full HP, but takes double damage from Spellcaster-type attackers.',
  },
};
